# Task automation for uploadDemoAWS
# https://taskfile.dev/

version: '3'

vars:
  AWS_PROFILE: personal
  AWS_REGION: eu-central-1
  STACK_NAME: upload-demo-stack
  MAIN_BINARY: bootstrap
  PRETOKEN_BINARY: lambda/pre-token/bootstrap
  BUILD_DIR: .aws-sam/build

tasks:
  # Build all Lambda function binaries for Linux
  build:
    desc: Build all Go Lambda functions for Linux AMD64
    cmds:
      - ./build.sh
    sources:
      - "cmd/lambda/**/*.go"
      - "internal/**/*.go"
      - "lambda/pre-token/**/*.go"
      - go.mod
      - go.sum
      - build.sh
    generates:
      - ".aws-sam/build/UploadFunction/function.zip"
      - ".aws-sam/build/PreTokenGenerationLambda/function.zip"

  # Package pre-built functions and prepare for deployment
  sam-package:
    desc: Package SAM application with pre-built binaries
    cmds:
      # First build Go binaries with our script
      - task: build
      # Use SAM package command to create deployment package
      - sam package --s3-bucket aws-sam-cli-managed-default-samclisourcebucket-gjzdgbfvwjgj --output-template-file packaged.yaml --profile {{.AWS_PROFILE}} --region {{.AWS_REGION}}

  # Deploy the complete stack
  deploy:
    desc: Deploy the CloudFormation stack using SAM
    cmds:
      - task: sam-package
      - sam deploy --template-file packaged.yaml --stack-name {{.STACK_NAME}} --profile {{.AWS_PROFILE}} --capabilities CAPABILITY_NAMED_IAM --region {{.AWS_REGION}} --no-fail-on-empty-changeset

  # Start local API for testing
  local:
    desc: Start local API Gateway for testing
    cmds:
      - task: sam-build
      - sam local start-api --profile {{.AWS_PROFILE}}

  # Run Go tests
  test:
    desc: Run Go unit tests
    cmds:
      - go test -v ./...

  # Format and lint Go code
  fmt:
    desc: Format Go code and run static analysis
    cmds:
      - go fmt ./...
      - go vet ./...
      - go mod tidy

  # Clean build artifacts
  clean:
    desc: Clean build artifacts and SAM cache
    cmds:
      - rm -f {{.BINARY_NAME}}
      - rm -rf {{.BUILD_DIR}}
      - rm -rf .aws-sam

  # Delete the CloudFormation stack
  delete:
    desc: Delete the CloudFormation stack
    cmds:
      - sam delete --stack-name {{.STACK_NAME}} --profile {{.AWS_PROFILE}} --region {{.AWS_REGION}} --no-prompts

  # Get Cognito user pool information for testing
  info:
    desc: Display Cognito User Pool and Client information
    cmds:
      - aws cognito-idp list-user-pools --max-items 10 --profile {{.AWS_PROFILE}} --query "UserPools[?Name=='upload-demo-user-pool']"
      - aws cognito-idp list-user-pool-clients --user-pool-id $(aws cognito-idp list-user-pools --max-items 10 --profile {{.AWS_PROFILE}} --query "UserPools[?Name=='upload-demo-user-pool'].Id" --output text) --profile {{.AWS_PROFILE}}

  # Create test users (run after deployment)
  create-users:
    desc: Create test users in Cognito User Pool
    cmds:
      - echo "Creating test users in Cognito User Pool..."
      - |
        USER_POOL_ID=$(aws cognito-idp list-user-pools --max-items 10 --profile {{.AWS_PROFILE}} --query "UserPools[?Name=='upload-demo-user-pool'].Id" --output text)
        aws cognito-idp admin-create-user --user-pool-id $USER_POOL_ID --username user-tenant-a --message-action SUPPRESS --temporary-password TempPass123! --profile {{.AWS_PROFILE}}
        aws cognito-idp admin-create-user --user-pool-id $USER_POOL_ID --username user-tenant-b --message-action SUPPRESS --temporary-password TempPass123! --profile {{.AWS_PROFILE}}
        aws cognito-idp admin-set-user-password --user-pool-id $USER_POOL_ID --username user-tenant-a --password TestPass123! --permanent --profile {{.AWS_PROFILE}}
        aws cognito-idp admin-set-user-password --user-pool-id $USER_POOL_ID --username user-tenant-b --password TestPass123! --permanent --profile {{.AWS_PROFILE}}